name: Android (V2 minimal, parse-safe)

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List repo
        run: ls -lah

      - name: Optional unzip latest zip if no pubspec.yaml
        id: pickzip
        shell: bash
        run: |
          set -euo pipefail
          if [ -f pubspec.yaml ]; then
            echo "zipmode=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          SEL="$(ls -1t *.zip 2>/dev/null | head -n1 || true)"
          if [ -z "${SEL}" ]; then
            SEL="$(find . -maxdepth 4 -type f -name '*.zip' -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -n1 | cut -d' ' -f2- || true)"
          fi
          if [ -n "${SEL}" ]; then
            echo "zipmode=true" >> "$GITHUB_OUTPUT"
            echo "zip=${SEL}" >> "$GITHUB_OUTPUT"
            unzip -q "${SEL}" -d .
          else
            echo "zipmode=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Detect flutter project dir
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          DIR="$(find . -maxdepth 6 -type f -name pubspec.yaml | head -n1 | xargs -I{} dirname {} || true)"
          if [ -z "${DIR}" ]; then
            echo "pubspec.yaml not found"
            exit 66
          fi
          echo "project_dir=${DIR}" >> "$GITHUB_OUTPUT"
          echo "Project dir: ${DIR}"

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter (stable latest)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Clean caches (non-interactive)
        working-directory: ${{ steps.detect.outputs.project_dir }}
        shell: bash
        run: |
          set -euo pipefail
          flutter --version
          flutter clean || true
          rm -rf "$HOME/.pub-cache" || true
          dart pub cache clean --force || true
          rm -f pubspec.lock || true
          flutter precache --force

      - name: Pub upgrade (keep constraints, but try to最新)
        working-directory: ${{ steps.detect.outputs.project_dir }}
        shell: bash
        run: |
          set -euo pipefail
          flutter pub upgrade --major-versions || true
          flutter pub get

      - name: Patch Android to Embedding V2 (safe edits)
        working-directory: ${{ steps.detect.outputs.project_dir }}
        shell: bash
        run: |
          set -euo pipefail
          [ -d android ] || exit 0

          # settings.gradle: 确保 plugin-loader
          if [ -f android/settings.gradle ]; then
            if ! grep -q 'dev.flutter.flutter-plugin-loader' android/settings.gradle; then
              {
                echo ''
                echo 'plugins {'
                echo '  id("dev.flutter.flutter-plugin-loader") version "1.0.0"'
                echo '  id("com.android.application") version "8.3.1" apply false'
                echo '  id("org.jetbrains.kotlin.android") version "1.9.24" apply false'
                echo '}'
              } >> android/settings.gradle
            fi
          fi

          # gradle wrapper 升到 8.7
          if [ -f android/gradle/wrapper/gradle-wrapper.properties ]; then
            sed -i -E 's#distributionUrl=.*#distributionUrl=https\\://services.gradle.org/distributions/gradle-8.7-bin.zip#g' android/gradle/wrapper/gradle-wrapper.properties
          fi

          # app/build.gradle: SDK 与插件
          if [ -f android/app/build.gradle ]; then
            sed -i -E 's/compileSdk\s*=?\s*[0-9]+/compileSdk 35/g' android/app/build.gradle || true
            sed -i -E 's/compileSdkVersion\s+[0-9]+/compileSdkVersion 35/g' android/app/build.gradle || true
            sed -i -E 's/minSdk\s*=?\s*[0-9]+/minSdk 23/g' android/app/build.gradle || true
            sed -i -E 's/minSdkVersion\s+[0-9]+/minSdkVersion 23/g' android/app/build.gradle || true
            sed -i -E 's/targetSdk\s*=?\s*[0-9]+/targetSdk 35/g' android/app/build.gradle || true
            sed -i -E 's/targetSdkVersion\s+[0-9]+/targetSdkVersion 35/g' android/app/build.gradle || true
          fi

          # Manifest: 去 v1 痕迹 + 加 V2 标记 + 权限
          find android/app/src -type f -name AndroidManifest.xml | while read -r M; do
            sed -i 's/android:name="io\.flutter\.app\.FlutterApplication"//g' "$M" || true
            if ! grep -q 'flutterEmbedding' "$M"; then
              awk '{print} /<application[^>]*>/ && !i {print "        <meta-data android:name=\"flutterEmbedding\" android:value=\"2\"/>"; i=1}' "$M" > "$M.__tmp__" && mv "$M.__tmp__" "$M"
            fi
            if echo "$M" | grep -q '/src/main/'; then
              if ! grep -q 'POST_NOTIFICATIONS' "$M"; then
                awk '{print} /<manifest[^>]*>/ && !j {print "    <uses-permission android:name=\"android.permission.POST_NOTIFICATIONS\"/>"; j=1}' "$M" > "$M.__tmp__" && mv "$M.__tmp__" "$M"
              fi
              if ! grep -q 'SCHEDULE_EXACT_ALARM' "$M"; then
                awk '{print} /<manifest[^>]*>/ && !k {print "    <uses-permission android:name=\"android.permission.SCHEDULE_EXACT_ALARM\"/>"; k=1}' "$M" > "$M.__tmp__" && mv "$M.__tmp__" "$M"
              fi
            fi
          done

          # MainActivity: 强制 V2 Activity
          MA_KT="$(find android/app/src -type f -name MainActivity.kt | head -n1 || true)"
          MA_JAVA="$(find android/app/src -type f -name MainActivity.java | head -n1 || true)"
          if [ -n "${MA_KT}" ]; then
            sed -i 's#io\.flutter\.app\.FlutterActivity#io.flutter.embedding.android.FlutterActivity#g' "${MA_KT}" || true
            grep -q '^class MainActivity' "${MA_KT}" && sed -i -E 's/^class\s+MainActivity.*$/class MainActivity: FlutterActivity()/' "${MA_KT}" || true
          elif [ -n "${MA_JAVA}" ]; then
            sed -i 's#io\.flutter\.app\.FlutterActivity#io.flutter.embedding.android.FlutterActivity#g' "${MA_JAVA}" || true
          fi

      - name: Build APK (capture logs)
        id: buildapk
        working-directory: ${{ steps.detect.outputs.project_dir }}
        shell: bash
        run: |
          set -euo pipefail
          ( set -o pipefail; flutter build apk -v 2>&1 | tee build_apk.log )

      - name: Gradle fallback assembleRelease
        if: failure()
        working-directory: ${{ steps.detect.outputs.project_dir }}/android
        shell: bash
        run: |
          set -o pipefail
          if [[ -x "./gradlew" ]]; then
            ( ./gradlew :app:assembleRelease --stacktrace --no-daemon 2>&1 | tee ../gradle_build.log ) || true
          fi

      - name: Annotate compiler errors
        if: always()
        working-directory: ${{ steps.detect.outputs.project_dir }}
        shell: bash
        run: |
          set -euo pipefail
          echo "=== Flutter build log ==="
          [ -f build_apk.log ] && grep -nE "(^e: |\\.kt:[0-9]+:|\\.java:[0-9]+:|^FAILURE:)" build_apk.log || true
          echo "=== Gradle build log ==="
          [ -f gradle_build.log ] && grep -nE "(: error:|\\.kt:[0-9]+:|\\.java:[0-9]+:|^FAILURE:)" gradle_build.log || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-and-logs
          path: |
            ${{ steps.detect.outputs.project_dir }}/build/app/outputs/flutter-apk/app-release.apk
            ${{ steps.detect.outputs.project_dir }}/build_apk.log
            ${{ steps.detect.outputs.project_dir }}/gradle_build.log
